DROP DATABASE quartz;
DROP ROLE quartz;
CREATE ROLE quartz WITH PASSWORD 'quartz' LOGIN NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE quartz WITH OWNER = quartz ENCODING = 'UTF8' TEMPLATE = template0 LC_COLLATE = 'C' LC_CTYPE = 'C';